### PR TITLE
Extract addLabel function

### LINKED ISSUE #14: [refactor] addLabel function
function addLabel can be defined outside of the map function scope https://github.com/eHealthAfrica/angular-couch-query/blob/master/src/eHealth.couchQuery/services/lucene-query-factory.js#L73-L81

### PR DESCRIPTION
**Pull request by obdulia-losantos**
Closes #14

### CODE REVIEW

**Comment by emig** [comment]
@obdulia-losantos if the addLabel is only used inside the getSeach... it makes sense to define it in that scope  (a kind of private function only used by that 'client') , but outside the scope of the .map function

**Comment by obdulia-losantos** [comment]
If the performance is and issue in the search then to extract the function saves time and space...

**Comment by emig** [comment]
Ok, is fine with me then. Can you update the CHANGELOG please, we put it in unreleased for now? :japanese_ogre:

**Comment by obdulia-losantos** [comment]
Updated!

**Pull request merged**
